AWSTemplateFormatVersion: 2010-09-09
Resources:
  AppRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: aws-webapp-exercise
Outputs:
  AppRepositoryRef:
    Value: !Ref AppRepository
    Export:
      Name: AppRepositoryRef
